[theme]
# Primary accent color for interactive elements.
primaryColor = "#fcc860"

# Background color for the main content area.
backgroundColor = "#12141d"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#1e2029"

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "Inter"
font = "sans serif"